const CONSTANTS = {
  SOCKET_EVENTS: {
    CREATE_MESSAGE: 'CREATE_MESSAGE',
    MESSAGE_CREATED: 'MESSAGE_CREATED',
    CREATE_MESSAGE_ERROR: 'CREATE_MESSAGE_ERROR',
  },
};

export default CONSTANTS;
